name: Image build
on:
  # elke nieve versie
  release:
    types: [published]
    tags:
      - '*'
  # Manueel starte
  workflow_dispatch:

jobs:
  docker_build: 
    runs-on: ubuntu-latest
 
    steps:
    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
         echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
         echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: Build base image
      run: |
        echo $SOURCE_NAME
        echo $SOURCE_BRANCH
        echo $SOURCE_TAG
      env:
        SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
        SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
        SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --build-arg Version=${{ steps.get_version.outputs.VERSION }} --file Dockerfile --tag xmrig-docker-unraid:latest
    - name: Publish to Registry
      #pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ziggyds/xmrig
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        #tags: "latest,${{ env.STATE_RELEASE_VERSION }}"
        tags: "latest,${{ steps.get_version.outputs.VERSION }}"