name: Image build
on:
  # elke nieve versie, elke change
  release:
    types:
    - published
    - unpublished
    - created
    - edited
    - deleted
    - prereleased
    - released

  # Manueel starte
  workflow_dispatch:

jobs:
  docker_build: 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - id: fetch-latest-release
      uses: thebritican/fetch-latest-release@v2.0.0
      with:
        github_token: ${{ github.token }}
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "ziggyds/xmrig-build"
        version: "tags/${{ steps.fetch-latest-release.outputs.tag_name }}"
        file: "xmrig-${{ steps.fetch-latest-release.outputs.tag_name }}-lin64.tar.gz"
        target: "xmrig.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg VERSION=${{ steps.fetch-latest-release.outputs.tag_name }} --tag xmrig-docker-unraid:${{ steps.fetch-latest-release.outputs.tag_name }}
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ziggyds/xmrig
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tags: "latest,${{ steps.fetch-latest-release.outputs.tag_name }}"
